### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by helloworldkr** [agermanidis/videodigest#4]
Getting the following error

File "/usr/local/bin/videodigest", line 57
    return sum(map(lambda (start, end): end-start, regions))
                          ^
SyntaxError: invalid syntax

**Comment by srichakradhar** [comment]
That is because the ability to unpack tuple parameters was removed in Python 3. [stackoverflow](https://stackoverflow.com/questions/11328312/python-lambda-does-not-accept-tuple-argument)
change it to     `return sum(map(lambda region: region[1]-region[0], regions))`.
